### ISSUE TITLE
Wrong `authorization` header for API calls after signing in

### ISSUE THREAD

**Issue by sdvg** [hoodiehq/hoodie-admin-client#4]
The `authorization` header still starts with `Bearer` instead of `Session`.

Steps to reproduce:

* `git clone https://github.com/hoodiehq/hoodie-app-tracker.git`
* Open http://127.0.0.1:8080/hoodie/admin/login
* Sign in

> Error while processing route: accounts Authorization header missing UnauthorizedError: Authorization header missing

> UnauthorizedError: Authorization header missing

**Comment by gr2m** [comment]
I’m looking into it

**Comment by gr2m** [comment]
I’ve tested it with the latest `@hoodie/admin` and it works now. You might need to clear your localStorage in your browser or test it in inkognito / private window
